name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master  # Adjust if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build  # Replace with your app's build command, or remove if not applicable

      - name: Zip application
        run: zip -r app.zip . -x ".git/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Add in GitHub Secrets
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Add in GitHub Secrets
          application_name: ${{ secrets.EB_APP_NAME }}  # e.g., "todo", "todo-backend"
          environment_name: ${{ secrets.EB_ENV_NAME }}  # e.g., "Todo-env"
          region: ${{ secrets.AWS_REGION }}  # e.g., "us-east-2"
          version_label: "v${{ github.run_number }}"
          deployment_package: app.zip

      - name: Verify Deployment
        run: echo "Deployment completed to Elastic Beanstalk: ${{ secrets.EB_APP_NAME }} in ${{ secrets.EB_ENV_NAME }}"
