name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master # Replace with the branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify your Node.js version
          cache: 'npm'

      # Step 3: Install dependencies and build the React app
      - name: Install dependencies
        run: |
          npm install

      - name: Build React app
        run: |
          npm run build
        working-directory: ./DoToList-AzureDevOps # Change this if your React app is in a different directory

      # Step 4: Package the application
      - name: Zip the application
        run: |
          zip -r application.zip . -x "**/node_modules/**" "**/DoToList-AzureDevOps/node_modules/**" "**/.*"
        
      # Step 5: Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          version_label: ${{ github.run_number }}
          deployment_package: application.zip

      # Step 6: Notify if deployment is successful
      - name: Deployment success
        if: ${{ success() }}
        run: echo "Application successfully deployed to Elastic Beanstalk!"

