name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install

    - name: Create Procfile for Elastic Beanstalk
      run: |
        echo "web: npm run dev" > Procfile

    - name: Install AWS Elastic Beanstalk CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install awsebcli

    - name: Build project
      run: npm run build

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'
        APPLICATION_NAME: 'todo'
        ENVIRONMENT_NAME: 'Todo-env'
      run: |
        # Initialize Elastic Beanstalk with Node.js platform
        eb init -p node.js --region $AWS_REGION

        # Check if environment exists
        eb status $ENVIRONMENT_NAME || {
          echo "Environment $ENVIRONMENT_NAME does not exist. Creating a new environment."
          eb create $ENVIRONMENT_NAME --region $AWS_REGION
        }

        # Use the environment and deploy
        eb use $ENVIRONMENT_NAME
        eb deploy

    - name: Clean up
      run: |
        rm Procfile
